version: "3.6"
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine3.17
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wg
    networks:
      - postgres
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
    restart: unless-stopped

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped

  wireguard:
    build:
      context: .
      dockerfile: Dockerfile.wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_GRPC_API_HOST=0.0.0.0
      - WG_GRPC_API_PORT=3000
      - WG_GRPC_API_SWAGGER=true
      - WG_GRPC_API_TOKENS=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTY4OTc4NTEwNSwiZXhwIjoxNjg5Nzg4NzA1fQ.lQWZuJVDmz1dUoYz8Y1PdKZxL4pJpIbHCf4Etfm4hx4
      - WG_GRPC_API_DB_HOST=postgres
      - WG_GRPC_API_DB_PORT=5432
      - WG_GRPC_API_DB_NAME=wg
      - WG_GRPC_API_DB_USERNAME=postgres
      - WG_GRPC_API_DB_PASSWORD=postgres
    networks:
      - postgres
    ports:
      - 51820:51820/udp
      - 127.0.0.1:3000:3000/tcp
    depends_on:
      postgres:
        condition: service_healthy
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgadmindata:
    driver: local
