version: '3'
services:
  rdb:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - '6379:6379'
    entrypoint: redis-server --save 60 1 --appendonly yes --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
