# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
  GO111MODULE: "on"

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1
    
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v ./...
